OUTPUT = generated
DIR = src
CC = g++

eratos: $(DIR)/Eratosthenes.c
	$(CC) -o ./$(OUTPUT)/eratos $(DIR)/Eratosthenes.c 
	./$(OUTPUT)/eratos

modExp: $(DIR)/ModExp.c
	$(CC) -o ./$(OUTPUT)/modExp $(DIR)/ModExp.c
	./$(OUTPUT)/modExp
